docker:
  image: yegor256/rultor-image:1.19.0
install: |-
  sudo gem install texsc:0.6.0
  sudo gem install texqc:0.6.0
  sudo apt-get -y update
  sudo apt-get -y install aspell
  sudo apt-get -y install ghostscript
merge:
  script: |-
    make